DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS rabbits;
DROP TABLE IF EXISTS horses;
DROP TABLE IF EXISTS birds;
DROP TABLE IF EXISTS barnyard;
DROP TABLE IF EXISTS small_furry;
DROP TABLE IF EXISTS scales_fins_others;
DROP TABLE IF EXISTS postcodes;


CREATE TABLE "dogs" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
); 

CREATE TABLE "cats" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
); 

CREATE TABLE "rabbits" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
); 

CREATE TABLE "horses" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
); 

CREATE TABLE "birds" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
);

CREATE TABLE "barnyard" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
); 

CREATE TABLE "small_furry" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
); 

CREATE TABLE "scales_fins_others" (
	"id" integer PRIMARY KEY,
	"name" varchar,
	"age" varchar,
	"gender" varchar,
	"size" varchar,
	"mixed" varchar,
	"primary_breed" varchar,
	"secondary_breed" varchar,
	"coat_length" varchar,
	"primary_color" varchar,
	"secondary_color" varchar,
	"declawed" varchar,
	"house_trained" varchar,
	"shots_current" varchar,
	"spayed_neutered" varchar,
	"special_needs" varchar,
	"good_with_cats" varchar,
	"good_with_children" varchar,
	"good_with_dogs" varchar,
	"species" varchar,
	"photo" varchar,
	"address" varchar,
	"city" varchar,
	"state" varchar,
	"postcode" varchar,
	"country" varchar,
	"status" varchar
); 

CREATE TABLE postcodes (
	"postcode" varchar,
	"latitude" decimal(8,6),
	"longitude" decimal(8,5)
);

SELECT * FROM postcodes;